#!/bin/bash
# name: all
# version: 0.2.2
# Copyright 2017 SMB, MIT License

BASE_DIR="$(cd "$(dirname "${0}")" && pwd -P)"

# Customize
REPOS="gamecode smb-data.pk3dir smb-maps.pk3dir"
DATA_DIR=${BASE_DIR}/data
DEV_DIR=${HOME}/xonotic/smb
USER_DIR=${HOME}/.supermechanicalbros
USER_DATA_DIR=${USER_DIR}/data
MAPS_DIR=${DATA_DIR}/xonotic-sxb.pk3dir
GMQCC_DIR=${DEV_DIR}/gmqcc
GAMECODE_DIR=${DEV_DIR}/gamecode
ENGINE_DIR=${DEV_DIR}/supermechbros/darkplaces/
SMB_BIN=darkplaces-sdl

# Internal Constants
SCRIPT_NAME=$(basename $0 .sh)
VERSION=$(awk 'NR == 3 {print $3; exit}' $0)

# Helpers
_check_dir() {
    local _dir=$1
    if [[ ! -d ${_dir} ]]; then
        echo "[ ERROR ] Unable to locate '${_dir}' directory."; exit 1
    fi
}

_fix_windows_path() {
    export PATH="$d0/misc/buildfiles/win64:$d0/d0_blind_id/.libs:$PATH"
}

_get_engine_dir() {
    relative_dir=${ENGINE_DIR}
    _check_dir ${relative_dir}
    export SMB_DIR=$(cd ${relative_dir}; pwd)
}

_get_dev_dir() {
    relative_dir=$(dirname $0)/../
    _check_dir ${relative_dir}
    if [[ "$(cd $(dirname $0)/../; basename $(pwd))" == "smb" ]]; then
        export DEV_DIR=$(cd ${relative_dir}; pwd)
    else
        echo "the parent directory needs to be named 'smb', I guess."
        exit 1
    fi
}

# Build Tasks

smb_build() {

    mkdir -p ${DEV_DIR} && \
        cd ${DEV_DIR}

    # Clone or Update deps
    if [[ ! -d ${GMQCC_DIR} ]]; then
        git clone https://gitlab.com/xonotic/gmqcc.git && cd ${GMQCC_DIR}
    else
        cd ${GMQCC_DIR} && git fetch && git pull --rebase
    fi
    make

    # Clone or Update gamecode
    if [[ ! -d ${GAMECODE_DIR} ]]; then
      git clone git@github.com:SuperMechBros/gamecode.git && cd ${GAMECODE_DIR}
    else
        cd ${GAMECODE_DIR} && git fetch && git pull --rebase
    fi
    make

    cd ${DATA_DIR}

    # Clone or Update
    for r in ${DATA_REPOS}; do
        echo "Updating: ${r}"
        if [[ ! -d ${r} ]]; then
            git clone git@github.com:SuperMechBros/${r}.git && cd ${r}
        else
            cd ${r} && git fetch && git pull --rebase
        fi
        cd ${DATA_DIR}
    done

    # Build
    cd ${DEV_DIR}/gamecode && \
        ./update.sh && \
        ./build.sh

    # Move mod
    mkdir -p ${USER_DATA_DIR} && \
        cp *.dat ${USER_DATA_DIR}
}

smb_build_maps() {
    cd ${DATA_DIR}
    if [[ ! -d ${MAPS_DIR} ]]; then
        git clone git@github.com:z/xonotic-sxb.pk3dir.git && cd ${MAPS_DIR}
    else
        cd ${MAPS_DIR} && git fetch && git pull --rebase
    fi
    if [[ ! -f ${MAPS_DIR}/build.conf ]]; then
        echo -e "XONDIR=${HOME}/xonotic/xonotic\nRADIANTDIR=${HOME}/xonotic/xonotic/netradiant/install" > ${MAPS_DIR}/build.conf
    fi
    ./build.sh --maps-all
}

smb_update() {
    echo "git pull --rebase all the things!"
}

smb_run() {
    ${SMB_DIR}/${SMB_BIN} -smb $@
}

# Meta

_version() {
    echo ${VERSION}
}

_help() {
    echo "./all

FLAGS
    --version              prints the version string

COMMANDS

    build                  update dependencies, builds everything
    build_maps             update dependencies, builds maps
    run                    runs Super Mechanical Bros.

EXAMPLES

    # update dependencies, builds everything
    ./all build

    # update dependencies, builds maps
    ./all build_maps

    # runs the game
    ./all run

    # Override the path to Super Mechnical Bros.
    # (normally assumed from relative location of this script)
    SMB_DIR=\$HOME/some/other/dir; ./all --version
"
}


# Init

# Allow for overriding the path assumption
# SMB_DIR=$HOME/some/other/dir; ./all --version
if [[ -z ${SMB_DIR} ]]; then
    _get_engine_dir
else
    _check_dir ${SMB_DIR}
fi

case "`uname`" in
    MINGW*|Win*)        _fix_windows_path;
esac

case $1 in
    # flags
    '--version')        _version;;
    # commands
    'build')            smb_build;;
    'build_maps')       shift; smb_build_maps $@;;
    'run')              shift; smb_run $@;;
    # default
    *)                  _help; exit 0;;
esac
